"""initial migration

Revision ID: 72751a37643b
Revises: 
Create Date: 2025-05-06 20:14:06.835231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72751a37643b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soldiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_soldier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_soldier_id'], ['soldiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machines')
    op.drop_table('soldiers')
    # ### end Alembic commands ###
